name: Attest BBC Technology RSS Feed

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  create-attestation:
    uses: kipz/url-oracle/.github/workflows/create-attestation.yml@main
    with:
      url: 'http://newsrss.bbc.co.uk/rss/newsonline_uk_edition/technology/rss.xml'
    permissions:
      id-token: write
      contents: write
      actions: read

  manage-releases:
    needs: create-attestation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: "Download attestation.json from previous job"
      uses: actions/download-artifact@v4
      with:
        name: attestation.json

    - name: Check for existing release
      id: release_check
      run: |
        # Get the content digest from the attestation and remove sha256: prefix
        CONTENT_DIGEST=$(jq -r '.payload.content_digest' attestation.json | sed 's/^sha256://')
        echo "Content digest: $CONTENT_DIGEST"
        
        # Check if a release with this content digest already exists
        RELEASE_EXISTS=false
        for tag in $(gh api repos/${{ github.repository }}/tags --jq '.[].name' 2>/dev/null || echo ""); do
          if [[ "$tag" == "content-$CONTENT_DIGEST" ]]; then
            RELEASE_EXISTS=true
            break
          fi
        done
        
        if [[ "$RELEASE_EXISTS" == "true" ]]; then
          echo "✅ Release with content digest $CONTENT_DIGEST already exists"
          echo "release_exists=true" >> $GITHUB_OUTPUT
        else
          echo "🔄 No existing release found for content digest $CONTENT_DIGEST"
          echo "release_exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Create release if needed
      if: steps.release_check.outputs.release_exists != 'true'
      run: |
        CONTENT_DIGEST=$(jq -r '.payload.content_digest' attestation.json | sed 's/^sha256://')
        
        # Create release with content digest tag
        gh release create "content-$CONTENT_DIGEST" \
          --title "BBC Technology RSS Feed Attestation - Content Digest: $CONTENT_DIGEST" \
          --notes "GitHub attestation for content digest $CONTENT_DIGEST" \
          attestation.json
        
        echo "✅ Created release with tag: content-$CONTENT_DIGEST"
        
    - name: Skip release creation
      if: steps.release_check.outputs.release_exists == 'true'
      run: |
        echo "⏭️  Skipping release creation - content digest already attested"
        echo "Existing release: content-$CONTENT_DIGEST"
